"""
Pydantic schemas for all data structures across ScholarSync.
Used by agents, workflow state management, and API request/response models.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────

class SubTaskType(str, Enum):
    ENTITIES = "entities"
    METHODOLOGY = "methodology"
    FINDINGS = "findings"
    RISKS = "risks"
    CLAIMS = "claims"
    COMPARISON = "comparison"


class PipelineStatus(str, Enum):
    PENDING = "pending"
    INGESTING = "ingesting"
    PLANNING = "planning"
    EXTRACTING = "extracting"
    BUILDING_GRAPH = "building_graph"
    VALIDATING = "validating"
    CORRECTING = "correcting"
    SYNTHESIZING = "synthesizing"
    COMPLETED = "completed"
    FAILED = "failed"


# ── Document Models ──────────────────────────────────────────────────

class DocumentChunk(BaseModel):
    """A single chunk from a parsed paper."""
    chunk_id: str
    paper_id: str
    paper_title: str
    text: str
    page_number: int = 0
    chunk_index: int = 0
    metadata: dict[str, Any] = Field(default_factory=dict)


class PaperMetadata(BaseModel):
    """Metadata extracted from a research paper."""
    paper_id: str
    filename: str
    title: str = ""
    authors: list[str] = Field(default_factory=list)
    year: Optional[int] = None
    total_pages: int = 0
    total_chunks: int = 0


# ── Extraction Models ───────────────────────────────────────────────

class Entity(BaseModel):
    """A named entity extracted from text."""
    name: str
    entity_type: str  # e.g., "method", "dataset", "metric", "author", "concept"
    description: str = ""
    source_paper: str = ""
    source_chunk_id: str = ""


class Relationship(BaseModel):
    """A relationship between two entities."""
    source_entity: str
    target_entity: str
    relationship_type: str  # e.g., "uses", "compares_with", "improves_upon"
    description: str = ""
    source_paper: str = ""


class ExtractedKnowledge(BaseModel):
    """Structured output from a worker agent for a single subtask."""
    subtask_type: SubTaskType
    paper_id: str
    paper_title: str = ""
    entities: list[Entity] = Field(default_factory=list)
    methodology: list[str] = Field(default_factory=list)
    findings: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    claims: list[str] = Field(default_factory=list)
    supporting_quotes: list[str] = Field(default_factory=list)
    source_chunk_ids: list[str] = Field(default_factory=list)
    relationships: list[Relationship] = Field(default_factory=list)


# ── Subtask Model ────────────────────────────────────────────────────

class SubTask(BaseModel):
    """A subtask generated by the manager agent."""
    task_id: str
    task_type: SubTaskType
    description: str
    assigned_paper_ids: list[str] = Field(default_factory=list)
    prompt: str = ""
    status: str = "pending"  # pending | running | completed | failed


# ── Validation Models ───────────────────────────────────────────────

class ClaimValidation(BaseModel):
    """Validation result for a single claim."""
    claim: str
    is_grounded: bool
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_evidence: list[str] = Field(default_factory=list)
    issues: list[str] = Field(default_factory=list)


class ValidationResult(BaseModel):
    """Complete validation result from the checking agent."""
    overall_score: float = Field(ge=0.0, le=1.0)
    is_valid: bool = False
    claim_validations: list[ClaimValidation] = Field(default_factory=list)
    hallucination_flags: list[str] = Field(default_factory=list)
    unsupported_claims: list[str] = Field(default_factory=list)
    correction_prompts: list[str] = Field(default_factory=list)
    feedback: str = ""


# ── Report Models ────────────────────────────────────────────────────

class CitationEntry(BaseModel):
    """A citation in the final report."""
    citation_id: str  # e.g., "[1]"
    paper_title: str
    authors: list[str] = Field(default_factory=list)
    year: Optional[int] = None
    relevant_quote: str = ""


class LiteratureReview(BaseModel):
    """The final synthesized literature review."""
    title: str
    summary: str = ""
    methodology_comparison: str = ""
    key_findings: str = ""
    cross_paper_insights: str = ""
    identified_risks: str = ""
    research_gaps: str = ""
    citations: list[CitationEntry] = Field(default_factory=list)
    safety_scorecard: dict[str, float] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=datetime.utcnow)


# ── Workflow State ───────────────────────────────────────────────────

class WorkflowState(BaseModel):
    """Complete state for the LangGraph pipeline."""
    # Input
    session_id: str = ""
    query: str = ""
    paper_ids: list[str] = Field(default_factory=list)

    # Pipeline tracking
    status: PipelineStatus = PipelineStatus.PENDING
    current_step: str = ""
    progress_messages: list[str] = Field(default_factory=list)

    # Manager output
    subtasks: list[SubTask] = Field(default_factory=list)

    # Worker outputs
    extractions: list[ExtractedKnowledge] = Field(default_factory=list)

    # Graph data
    entities: list[Entity] = Field(default_factory=list)
    relationships: list[Relationship] = Field(default_factory=list)

    # Validation
    validation_results: list[ValidationResult] = Field(default_factory=list)
    correction_count: int = 0

    # Final output
    final_report: Optional[LiteratureReview] = None
    report_markdown: str = ""

    # Errors
    errors: list[str] = Field(default_factory=list)


# ── API Models ───────────────────────────────────────────────────────

class UploadResponse(BaseModel):
    """Response after uploading papers."""
    session_id: str
    papers: list[PaperMetadata]
    total_chunks: int
    message: str


class QueryRequest(BaseModel):
    """Request to start a literature review pipeline."""
    session_id: str
    query: str


class QueryResponse(BaseModel):
    """Response after starting a query pipeline."""
    session_id: str
    status: PipelineStatus
    message: str


class ReportResponse(BaseModel):
    """Response with the generated report."""
    session_id: str
    status: PipelineStatus
    report: Optional[LiteratureReview] = None
    report_markdown: str = ""
    progress_messages: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = "ok"
    version: str = "1.0.0"
    services: dict[str, str] = Field(default_factory=dict)
